name: CI for Docker Build and Push

on:
  push:
    branches:
      - 'nexus-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Dockerfile information
        id: extract_info
        run: |
          DOCKERFILE_PATH="Dockerfile.java17"
          BASE_IMAGE=$(awk '/^FROM/ {gsub(":", "", $2); print $2$3}' $DOCKERFILE_PATH | sed 's/[^[:print:]]*$//')
          BRANCH_NAME=${GITHUB_REF#refs/heads/nexus-}
          TIMESHTAMP=$(date +"%d%m%Y%H%M%S")
          IMAGE_TAG="nexus3:$BASE_IMAGE-$BRANCH_NAME-$TIMESHTAMP"


          echo "dockerfile = $DOCKERFILE_PATH"
          echo "base image = $BASE_IMAGE"
          echo "nexus version = $BRANCH_NAME"
          echo "timeshtamp = $TIMESHTAMP"
          echo -n "image tag = $IMAGE_TAG"
          
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV
          echo -n "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
                    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3          

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TAG }}
