name: CI for Docker Build, Push, and Scan

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          if [ -f Dockerfile.java8 ]; then
            echo "DOCKERFILE_PATH=Dockerfile.java8" >> $GITHUB_ENV
            echo "JAVA_VERSION=java8" >> $GITHUB_ENV
          elif [ -f Dockerfile.java11 ]; then
            echo "DOCKERFILE_PATH=Dockerfile.java17" >> $GITHUB_ENV
            echo "JAVA_VERSION=java11" >> $GITHUB_ENV
          else
            echo "No suitable Dockerfile found"
            exit 1
          fi

      - name: Extract Dockerfile information
        id: extract_info
        run: |
          DOCKERFILE_PATH=${{ env.DOCKERFILE_PATH }}
          JAVA_VERSION=${{ env.JAVA_VERSION }}
          BASE_IMAGE=$(awk '/^FROM/ {gsub(":", "", $2); print $2$3}' $DOCKERFILE_PATH | sed 's/[^[:print:]]*$//')
          BRANCH_NAME=${GITHUB_REF#refs/heads/nexus-}
          TIMESTAMP=$(date +"%d%m%Y%H%M%S")
          IMAGE_TAG="nexus3:$BASE_IMAGE-$BRANCH_NAME-$JAVA_VERSION-$TIMESTAMP"

          echo "dockerfile = $DOCKERFILE_PATH"
          echo "base image = $BASE_IMAGE"
          echo "nexus version = $BRANCH_NAME"
          echo "timestamp = $TIMESTAMP"
          echo "image tag = $IMAGE_TAG"
          
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
                    
      - name: Login to Docker Hub
        if: ${{ env.DOCKERFILE_PATH }}
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ env.DOCKERFILE_PATH }}
        uses: docker/setup-buildx-action@v3          

      - name: Build and push
        if: ${{ env.DOCKERFILE_PATH }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_TAG }}

      - name: Docker Scout Scan
        id: scout_scan
        uses: docker/scout-action@v1.9.3
        with:
          command: quickview,cves
          sarif-file: scout-report.sarif
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        id: scout-report-artifact
        uses: actions/upload-artifact@v4.3.3
        if: always()
        with:
          name: docker-scout-report
          path: scout-report.sarif
        


